version: "2.1"

volumes:
  spotifycache:
  snapcast:

services:
  # Core services
  audio:
    build: balena-sound/core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317
    volumes:
      - snapcast:/var/cache/snapcast

  sound-supervisor:
    build: balena-sound/core/sound-supervisor
    network_mode: host
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1

  multiroom-server:
    build: balena-sound/core/multiroom/server
    restart: on-failure
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - snapcast:/var/cache/snapcast

  multiroom-client:
    build: balena-sound/core/multiroom/client
    restart: on-failure

  # Plugins
  bluetooth:
    build: balena-sound/plugins/bluetooth
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1

  airplay:
    build: balena-sound/plugins/airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

  spotify:
    build: balena-sound/plugins/spotify
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify

  upnp:
    build: balena-sound/plugins/upnp
    restart: on-failure
    network_mode: host
    ports:
      - 49494:49494

  # Network Manager
  wifi-connect:
    build: wifi-connect
    command: sh -c "sed
      -e 's/^\(iwgetid\)/# \1/'
      -e 's/# \(ip route\)/\1/'
      -i start.sh
      && exec bash start.sh"
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    labels:
      io.balena.features.dbus: "1"
    network_mode: host
    restart: always
